language: node_js
node_js:
	- 0.12.8
notifications:
	- darianosoares@hotmail.com
before_install:
	- npm i -g bower@1.7
	- npm i -g grunt-cli@0.1
	- npm i -g karma-cli@0.13
	- npm i -g protractor@1.5
	- webdriver-manager update
	- bower install
before_script:
	- grunt
	- cd dist
script:
	- karma start config/karma.conf.js --single-run --browsers PhantomJS