language: node_js
node_js:
- 0.12
notifications:
- darianosoares@hotmail.com
before_install:
- npm install -g bower@1.7
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.13
- npm install -g protractor@1.5
- webdriver-manager update
- bower install
- npm install
before_script:
- grunt
- cd dist
script:
- karma start config/karma.conf.js --single-run --browsers PhantomJS