language: node_js
notifications:
- darianosoares@hotmail.com
node_js:
- 0.12
services:
- mongodb
env:
	global:
	- NOVE_ENV: test
addons:
	sauce_connect: true
before_install:
- npm install -g bower@1.7
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.0
- npm install -g protractor@1.5
- webdriver-manager update
- bower install
before_script:
- node test/data.js
- grunt
- cd dist
script:
- karma start karma.conf.js --single-run --browsers PhantomJS
- node server &
- protractor config/protractor.js